### ISSUE TITLE
Bad training performance with hash encoding

### ISSUE THREAD

**Issue by wangjksjtu** [ashawkey/torch-ngp#5] opened 2022-02-01 20:12 UTC
Hi @ashawkey,

I cannot reproduce the training gifs you provided in README.md. Instead, I got the following results after training 200 epochs. Did I mess up something?

Command:
```
python train_nerf.py data/nerf/fox --workspace trial_nerf # fp16 and ff not enabled
```

Log info:
```
==> Finished Epoch 199.
==> Start Training Epoch 200, lr=0.000359 ...
==> Finished Epoch 200.
++> Evaluate at epoch 200 ...
==> Saving validation image to trial_nerf/validation/ngp_0200_0001.png
++> Evaluate epoch 200 Finished.
[INFO] New best result: 0.001995325554162264 --> 0.0019571746233850718
==> Start Test, save results to trial_nerf/results
```
NeRF-hash | NeRF-freq
:---: | :---:
![nerf_hash](https://user-images.githubusercontent.com/22170175/152043412-0f5be185-d695-4816-9f10-3b986952eeef.gif) | ![nerf_freq](https://user-images.githubusercontent.com/22170175/152043419-18c7f8e7-2f7f-43b1-b987-fe249fb1a44d.gif)

Thanks a lot!

**Comment by wangjksjtu** [comment] 2022-02-01 21:21
I tried the SDF scripts as well, the results are the same when trying to use the hash encoding. It cannot learn anything... Maybe there is something wrong with the `hashencoder.cu` or my compilation is wrong.

**Comment by ashawkey** [comment] 2022-02-02 02:03
You're right, thanks for spotting this! It's a bug caused by adding the `__half2` function. I recommend to use the fp16 mode which works well and trains/infers much faster before I fix the fp32 mode ;)

**Comment by ashawkey** [comment] 2022-02-02 02:11
fixed in https://github.com/ashawkey/torch-ngp/commit/30a8bf0fe91c0123ba475a11b2d853c7d7cfc776

**Comment by wangjksjtu** [comment] 2022-02-02 02:36
Yeah, it works as expected now! Thanks a lot!!

**Closed** 2022-02-02 02:37 UTC
